### ISSUE TITLE
OpenCL 3.0 issues to create

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/OpenCL-CTS#773]
This issue covers creating issues for all changes in OpenCL 3.0 that require CTS work that hasn't been done yet.

# Feature Optionality

### Shared Virtual Memory

See existing [SVM test suite](https://github.com/KhronosGroup/OpenCL-CTS/tree/master/test_conformance/SVM).

* [x] Need to add checks for lack of SVM support.
* [x] Evaluate how much can be tested without the OpenCL 2.0 memory consistency model / atomic support. (#887)

### Memory Consistency Model

See existing [C11 Atomics test suite](https://github.com/KhronosGroup/OpenCL-CTS/tree/master/test_conformance/c11_atomics).

This is likely to interact with many other OpenCL 2.x tests.

* [x] Need to update to cover at least OpenCL 1.2 (minimum) and OpenCL 2.0 level of support.

### Device Enqueue

See existing [Device Execution test suite](https://github.com/KhronosGroup/OpenCL-CTS/tree/master/test_conformance/device_execution).

This test suite may also be using program scope global variables.

* [x] Need to update to check for lack of device enqueue support.
* [x] Confirm: nothing needed for [`cl_khr_device_enqueue_local_arg_types`](https://www.khronos.org/registry/OpenCL/specs/2.2/html/OpenCL_Ext.html#cl_khr_device_enqueue_local_arg_types)? (#888)
    * It doesn't appear that this extension is supported by Clang, see: https://godbolt.org/z/rha8fy
    * AMD is supporting the extension and can contribute tests.  Work is still needed to upstream to Clang.

### Program Scope Global Variables

See existing [basic progvar test](https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/basic/test_progvar.cpp).

Recording medium due to likely interactions with other tests.

* [x] Need to add checks for lack of Program Scope Global Variable support. (#878)

### Non-Uniform Work Groups

See existing [Non-Uniform Work Groups test suite](https://github.com/KhronosGroup/OpenCL-CTS/tree/master/test_conformance/non_uniform_work_group).

* [x] Need to add checks for lack of Non-Uniform Work Groups support (https://github.com/KhronosGroup/OpenCL-CTS/issues/791).
* [x] Need to test for `get_enqueued_local_size`, etc. even when Non-Uniform Work Groups are not supported? (#877)

### Read-Write Images

See existing Read-Write Image tests in the [Images test suite](https://github.com/KhronosGroup/OpenCL-CTS/tree/master/test_conformance/images/kernel_read_write).

* [x] Need to add checks for lack of Read-Write Images support. (#894)

### Creating 2D Images from Buffers

Follow pattern for `cl_khr_image2d_from_buffer` in the [Images test suite](https://github.com/KhronosGroup/OpenCL-CTS/tree/master/test_conformance/images/kernel_read_write).

* [x] Check that no additional checks are needed beyond check for `cl_khr_image2d_from_buffer`. (#889)

### sRGB Images

See existing sRGB Image tests in the [Images test suite](https://github.com/KhronosGroup/OpenCL-CTS/tree/master/test_conformance/images/kernel_read_write).

* [x] Verify no checks are needed for optional sRGB Image support. (#892)

### Depth Images

See existing Depth Image tests in the [Images test suite](https://github.com/KhronosGroup/OpenCL-CTS/tree/master/test_conformance/images/kernel_read_write).

* [x] Verify no checks are needed for optional Depth Image support. (#892)

### Intermediate Language Programs

See existing [SPIR-V test suite](https://github.com/KhronosGroup/OpenCL-CTS/tree/master/test_conformance/spirv_new).

* [x] Need to add checks for lack of SPIR-V support?
* [x] Check for specialization constant testing.
* [x] Link between language features and SPIR-V capabilities.
* [x] Tests in SPIR-V new for each capability linked to an optional feature 

All covered by https://github.com/KhronosGroup/OpenCL-CTS/issues/794.

### Subgroups

See existing [Subgroups test suite](https://github.com/KhronosGroup/OpenCL-CTS/tree/master/test_conformance/subgroups).

* [x] Is anything needed beyond checks for `cl_khr_subgroups`?
* [x] Need to add checks for lack of subgroup IFP?

Covered by https://github.com/KhronosGroup/OpenCL-CTS/issues/795

### 3D Image Writes

Follow pattern for `cl_khr_3d_images_writes` in the [Images test suite](https://github.com/KhronosGroup/OpenCL-CTS/tree/master/test_conformance/images/kernel_read_write).

* [x] Check that no additional checks are needed beyond check for `cl_khr_3d_images_writes`. (#874)

### Generic Address Space @JeremyKemp 

See existing [Generic Address Space test suite](https://github.com/KhronosGroup/OpenCL-CTS/tree/master/test_conformance/generic_address_space).

Generic Address Space is also likely to have interactions with other tests, such as SVM.

* [x] Need to add checks for lack of Generic Address Space support. (#909)

### Required Features Beyond OpenCL 1.2

* [x] Test `clCloneKernel` under OpenCL 3.0 (Máté).
* [x] Test `clCreateCommandQueueWithProperties` under OpenCL 3.0. (#869, #890)
* [x] Test `clCreateSamplerWithProperties` under OpenCL 3.0. (#858)
* [x] Test  `NULL` / Zero Global Work Size under OpenCL 3.0.
* [x] Test `ctz` under OpenCL 3.0. (#882)
* [x] Test `get_global_linear_id` under OpenCL 3.0. (#883, #876)
* [x] Test `get_local_linear_id` under OpenCL 3.0. (#883, 876)
* [x] Add support for `-cl-std=CL3.0` compile option. (#879)

### Other Tasks

* [x] Test query for supported language features under OpenCL 3.0. (#762)
* [x] Generic framework for optional feature testing (https://github.com/KhronosGroup/OpenCL-CTS/issues/792).
* [x] Evaluate whether extension pragmas are required, and in which cases, in OpenCL C 3.0. (#886 but no longer in scope for 3.0)
* [x] Evaluate feature dependencies.  For example, do we require non-uniform work groups with device side enqueue?
* [x] Consider expanding test coverage in the pipes tests for pointers to all three address spaces (see https://gitlab.khronos.org/opencl/OpenCL-Docs/issues/235). (#895)
* [x] Consider expanding test coverage in the device enqueue tests for pointers to all three address spaces (see https://gitlab.khronos.org/opencl/OpenCL-Docs/issues/236). (#896)

### Identifying Feature Interactions

As-needed, identify features that currently interact that will need to be separated so one feature may be supported without requiring the other.
For example, generic address space tests currently use program scope global variables.
There are likely to be more of these.

### Behaviour of unsupported features and device query consistency

- [x] All API functions must be callable and return `CL_INVALID_OPERATION`/`NULL`/etc when not supported (#912)
- [x] `CL_DEVICE_MAX_READ_WRITE_IMAGE_ARGS` (#762, #912)
- [x] `CL_DEVICE_IMAGE_PITCH_ALIGNMENT` (#912)
- [x] `CL_DEVICE_IMAGE_BASE_ADDRESS_ALIGNMENT` (#912)
- [x] `CL_DEVICE_MAX_PIPE_ARGS` (#875)
- [x] `CL_DEVICE_PIPE_MAX_ACTIVE_RESERVATIONS` (#875)
- [x] `CL_DEVICE_PIPE_MAX_PACKET_SIZE` (#875)
- [x] `CL_DEVICE_MAX_GLOBAL_VARIABLE_SIZE` (#762, #912)
- [x] `CL_DEVICE_QUEUE_ON_DEVICE_PROPERTIES` (#875)
- [x] `CL_DEVICE_QUEUE_ON_DEVICE_PREFERRED_SIZE` (#875)
- [x] `CL_DEVICE_QUEUE_ON_DEVICE_MAX_SIZE` (#875)
- [x] `CL_DEVICE_MAX_ON_DEVICE_QUEUES` (#875)
- [x] `CL_DEVICE_MAX_ON_DEVICE_EVENTS` (#875)
- [x] `CL_DEVICE_SVM_CAPABILITIES` (#875)
- [x] `CL_DEVICE_MAX_NUM_SUB_GROUPS` (#762, #912)
- [x] `CL_DEVICE_SUB_GROUP_INDEPENDENT_FORWARD_PROGRESS` (#912)
- [x] `CL_DEVICE_ATOMIC_MEMORY_CAPABILITIES` (#875)
- [x] `CL_DEVICE_ATOMIC_FENCE_CAPABILITIES` (#875)
- [x] `CL_DEVICE_NON_UNIFORM_WORK_GROUP_SUPPORT` (#912)
- [x] `CL_DEVICE_WORK_GROUP_COLLECTIVE_FUNCTIONS_SUPPORT` (#762)
- [x] `CL_DEVICE_GENERIC_ADDRESS_SPACE_SUPPORT` (#875, #912)
- [x] `CL_DEVICE_DEVICE_ENQUEUE_CAPABILITIES` (#875)
- [x] `CL_DEVICE_PIPE_SUPPORT` (#875)
- [x] `CL_DEVICE_OPENCL_C_VERSION` (incl. consistency with supported features) (#897)
- [x] `CL_DEVICE_OPENCL_C_ALL_VERSIONS` (#897)
- [x] `CL_DEVICE_EXTENSIONS` (list of mandatory extensions) (#898)
- [x] Program initialization and clean up kernels (#903)

# Feature changes

- [x] Volatile on old-style atomics (https://github.com/KhronosGroup/OpenCL-Docs/issues/322, https://github.com/KhronosGroup/OpenCL-CTS/issues/908)
- [x] List of required image formats (#427, #629)

# New features

* [x] Add a test for OpenCL C consistency (see [related comment](https://gitlab.khronos.org/opencl/OpenCL-Docs/issues/227#note_244683)): check that if a device reports OpenCL C 3.0 for `CL_DEVICE_OPENCL_C_VERSION` then it also reports support for OpenCL C 2.0, and that it reports support for all optional feature macros. (#897)
* [x] Add a test for vector swizzles, including .xyzw, .rgbz, and .s012... swizzling (Dennis). (#891)
- [x] Feature macros query and consistency with compiler (#762)
- [x] `CL_QUEUE_PROPERTIES_ARRAY` query (#869)
- [x] `clCreateBufferWithProperties` (#857)
- [x] `clCreateImageWithProperties` (#857)
- [x] `clSetContextDestructorCallback` (#861)
- [x] `CL_PIPE_PROPERTIES` query (https://github.com/KhronosGroup/OpenCL-CTS/issues/991)
- [x] `CL_MEM_PROPERTIES` query (#857)
- [x] `CL_SAMPLER_PROPERTIES` query (#858)
- [x] Agreement between language versions reported and accepted `-cl-std` flags (#899)
- [x] New `CL_COMMAND_SVM_MIGRATE_MEM` `CL_EVENT_COMMAND_TYPE` (https://github.com/KhronosGroup/OpenCL-CTS/pull/856)
- [x] Extended versioning as a core feature (https://github.com/KhronosGroup/OpenCL-CTS/issues/992)
- [x] `CL_PLATFORM_HOST_TIMER_RESOLUTION`
- [x] `CL_DEVICE_VENDOR_ID` (#893)
- [x] `CL_DEVICE_PREFERRED_WORK_GROUP_SIZE_MULTIPLE`
- [x] Test that `memory_scope_all_devices` is present if `__opencl_c_atomic_scope_all_devices` is set. (https://github.com/KhronosGroup/OpenCL-CTS/issues/990)

**Comment by gwawiork** [comment]
- subgroups - is solved by https://github.com/KhronosGroup/OpenCL-CTS/pull/682. This cannot be merged until this https://github.com/KhronosGroup/OpenCL-CTS/pull/745
- Intermediate language programs - https://github.com/KhronosGroup/OpenCL-CTS/pull/717 and https://github.com/KhronosGroup/OpenCL-CTS/pull/719 solve two first items

**Comment by FranklandJack** [comment]
Issue created for `Need to add checks for lack of Non-Uniform Work Groups support.` https://github.com/KhronosGroup/OpenCL-CTS/issues/791

**Comment by bashbaug** [comment]
I have a very simple PR to test `CL_COMMAND_SVM_MIGRATE_MEM` here: https://github.com/KhronosGroup/OpenCL-CTS/pull/856

**Comment by gwawiork** [comment]
Test for clCreateBufferWithProperties and clCreateImageWithProperties #857

**Comment by gwawiork** [comment]
Test for `CL_SAMPLER_PROPERTIES` #858

**Comment by bashbaug** [comment]
PR #861 adds a test for `clSetContextDestructorCallback`.

**Comment by gwawiork** [comment]
I've started working on CL_​QUEUE_​PROPERTIES_​ARRAY

**Comment by bashbaug** [comment]
I have the start of an API Feature Consistency test here: https://github.com/KhronosGroup/OpenCL-CTS/pull/875.

**Comment by bashbaug** [comment]
I looked at the test for `clCloneKernel` [here](https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/api/test_clone_kernel.cpp) and I don't see anything that needs updating for OpenCL 3.0.  I think we can tick its box.

**Comment by bashbaug** [comment]
The test for `clCreateCommandQueueWithProperties` under OpenCL 3.0 will be covered by #869.  If we wanted a bit more coverage we could modify `test_api queue_properties` so it also works with the core `clCreateCommandQueueWithProperties` for OpenCL 2.0 and greater, in addition to the `cl_khr_create_command_queue` extension equivalent `clCreateCommandQueueWithPropertiesKHR`.

There is basic coverage for `clCreateSamplerWithProperties` for OpenCL 3.0 in `test_api get_sampler_info`.

**Comment by bashbaug** [comment]
I've looked at the test for a NULL / Global Work Size [here](https://github.com/KhronosGroup/OpenCL-CTS/blob/master/test_conformance/api/test_zero_sized_enqueue.cpp) and I don't see anything that needs updating for OpenCL 3.0.  I think we can tick its box.

**Comment by bashbaug** [comment]
Created https://github.com/KhronosGroup/OpenCL-CTS/issues/882 to track "Test ctz under OpenCL 3.0."  This should require only very minor changes to `test_integer_ops`.

**Comment by bashbaug** [comment]
Created https://github.com/KhronosGroup/OpenCL-CTS/issues/883 to track "Test get_global_linear_id under OpenCL 3.0" and "Test get_local_linear_id under OpenCL 3.0".  This should require only very minor changes to `test_basic get_linear_ids`.

**Comment by bashbaug** [comment]
Regarding the various device queries listed under "Behaviour of unsupported features and device query consistency", I believe all of these are tested under `computeinfo`.  The consistency parts will be tested under the new feature consistency test, see #875.  Is that sufficient or is more needed here?

**Comment by bashbaug** [comment]
FYI, the related spec issue for `Volatile on old-style atomics (TBD link issue)` is:

https://github.com/KhronosGroup/OpenCL-Docs/issues/322

**Comment by bashbaug** [comment]
I've created https://github.com/KhronosGroup/OpenCL-CTS/issues/887 to track the item "Evaluate how much can be tested without the OpenCL 2.0 memory consistency model / atomic support" as we discussed on today's call.

**Comment by bashbaug** [comment]
I've created #888 to track the item "Confirm: nothing needed for cl_khr_device_enqueue_local_arg_types?" as we discussed on today's call.

**Comment by bashbaug** [comment]
https://github.com/KhronosGroup/OpenCL-CTS/issues/889 tracks the item "Check that no additional checks are needed beyond check for cl_khr_image2d_from_buffer".  In practice, they may not be required, since I suspect most implementations that support this feature will also support the `cl_khr_image2d_from_buffer` extension.

**Comment by bashbaug** [comment]
#890 tracks the item "Test clCreateCommandQueueWithProperties under OpenCL 3.0".  This is nice-to-have and not must-have since we will have some coverage for this API when #869 is merged.

**Comment by FranklandJack** [comment]
With regards to the read-write image support, the test I mentioned in the call yesterday that we know is failing / being run unconditionally for a 3.0 device that optionally does not support read-write images is: `rw_image_access_qualifier` from `basic`. Since I couldn't see a ticket created for this yet I thought I'd put it here before I forget.

**Comment by FranklandJack** [comment]
With regard to the following checkboxes:
```
- [ ] Test ctz under OpenCL 3.0.
- [ ] Test get_global_linear_id under OpenCL 3.0.
- [ ] Test get_local_linear_id under OpenCL 3.0.
- [ ] Add support for -cl-std=CL3.0 compile option.
```
I have local patch to test ctz under OpenCL 3.0.
`get_global_linear_id` and `get_local_linear_id` is addressed in #876.
Adding support for -cl-std=CL3.0 is addressed in #879. Whether we decide to go with the approach taken in this PR will affect the `ctz` and `get_(local|global)_linear_id` since we can reuse the logic that selects the OpenCL C version.

**Comment by Jeremy-Kemp** [comment]
I've reviewed the required image formats within CTS.

The required format list for read **or** write is correct. Read **and** write is missing.

Existing issues #427 #629 track what is needed to resolve the coverage gap.

I've added those issues to the 3.0 board.

**Comment by Jeremy-Kemp** [comment]
#909 created to track generic address space.

**Comment by bashbaug** [comment]
Is the remaining "Memory Consistency Model" item covered by #907 or is more required?

**Comment by bashbaug** [comment]
There is some coverage for the following items in #912:

* All API functions must be callable and return CL_INVALID_OPERATION/NULL/etc when not supported
* CL_DEVICE_MAX_READ_WRITE_IMAGE_ARGS
* CL_DEVICE_IMAGE_PITCH_ALIGNMENT
* CL_DEVICE_IMAGE_BASE_ADDRESS_ALIGNMENT
* CL_DEVICE_MAX_GLOBAL_VARIABLE_SIZE
* CL_DEVICE_MAX_NUM_SUB_GROUPS
* CL_DEVICE_SUB_GROUP_INDEPENDENT_FORWARD_PROGRESS
    * Note, only if subgroups are not supported.  This query is also tested by `ifp_core` and `ifp_ext` in the subgroups suite.
* CL_DEVICE_GENERIC_ADDRESS_SPACE_SUPPORT
    * Note, only if pipes or device enqueue are supported.  This query is also tested by the generic address space tests.

**Comment by bashbaug** [comment]
There is coverage for CL_DEVICE_WORK_GROUP_COLLECTIVE_FUNCTIONS_SUPPORT in the existing work group tests, e.g. `work_group_any`.  The OpenCL C features test also could/should check for it, to ensure consistency between the API query and the OpenCL C query.

**Comment by bashbaug** [comment]
Test for CL_MEM_PROPERTIES was added by #857.

**Comment by alycm** [comment]
I have reviewed the unticked boxes and there are now only four left.  The memory consistency model box is says

> Need to update to cover at least OpenCL 1.2 (minimum) and OpenCL 2.0 level of support.

If that means that a device that reports minimum capabilities should be able to pass the C11 atomics tests then #907, #944, #954 did that.

**Comment by alycm** [comment]
I've filed issues for the last three unticked boxes:
* https://github.com/KhronosGroup/OpenCL-CTS/issues/990
* https://github.com/KhronosGroup/OpenCL-CTS/issues/991
* https://github.com/KhronosGroup/OpenCL-CTS/issues/992

As this ticket is for "issues to create" and now all the issues have been created I will close this issue.
